spring:
  application:
    name: albatime

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/albatime?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: albatime
    password: 8204

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect